# -*- coding: utf-8 -*-
"""Appends additional QBANK sections and the trial-generator; run AFTER gen_quiz.py builds QBANK.
Actually, we'll import from gen_quiz and extend."""
from gen_quiz import QBANK

# ----------------------- CNS -----------------------
QBANK["CNS"] = {"section_zh":"中樞神經腫瘤","section_en":"CNS Tumors","questions":[
  ("single","GBM 標準 Stupp regimen 的 RT 劑量與分次為？","The RT dose in the standard Stupp regimen for GBM is?",
    [("50 Gy/25 fx","50 Gy/25 fx"),("54 Gy/30 fx","54 Gy/30 fx"),("60 Gy/30 fx","60 Gy/30 fx"),("70 Gy/35 fx","70 Gy/35 fx")],"C",
    "Stupp 2005：60 Gy/30 fx + concurrent TMZ → adjuvant TMZ × 6 cycles。","Stupp 2005: 60 Gy/30 fx with concurrent TMZ, then adjuvant TMZ × 6 cycles."),
  ("single","下列何者是 GBM 最強的分子預測因子？","Which is the strongest molecular predictor of GBM outcome?",
    [("MGMT 甲基化","MGMT methylation"),("IDH1 突變","IDH1 mutation"),("EGFR amplification","EGFR amplification"),("1p/19q co-deletion","1p/19q co-deletion")],"A",
    "MGMT 甲基化預測 TMZ 反應與 OS 提升，是 GBM 治療決策關鍵；IDH1-wt 為 GBM 分子定義之一。","MGMT methylation predicts TMZ response and OS in GBM; IDH1-wt is a defining feature of glioblastoma."),
  ("single","低惡度膠質瘤 (LGG) RTOG 9802 高風險族群的標準治療是？","RTOG 9802 high-risk LGG standard treatment?",
    [("Observation","Observation"),("54 Gy RT alone","54 Gy RT alone"),("54 Gy RT + PCV","54 Gy RT + PCV chemotherapy"),("Temozolomide alone","Temozolomide alone")],"C",
    "RTOG 9802：高風險 LGG 加 PCV 化療延長 OS 約 5.5 年 (13.3 vs 7.8)。","RTOG 9802: RT + PCV extends OS ~5.5 years (13.3 vs 7.8) in high-risk LGG."),
  ("single","EORTC 26951 對 1p/19q co-del anaplastic oligodendroglioma 顯示？","EORTC 26951 for 1p/19q co-del anaplastic oligodendroglioma showed?",
    [("PCV 沒有幫助","PCV had no benefit"),("PCV + RT 顯著提升 OS","PCV + RT significantly improved OS"),("RT alone 較好","RT alone was superior"),("TMZ 優於 PCV","TMZ superior to PCV")],"B",
    "EORTC 26951 與 RTOG 9402：1p/19q co-del 病人 RT + PCV OS 顯著改善。","EORTC 26951 & RTOG 9402: 1p/19q co-deleted patients benefit significantly from RT + PCV."),
  ("single","老年 GBM (≥ 65) 短程 RT 常用劑量？","Common short-course RT dose for elderly GBM (≥ 65)?",
    [("30 Gy/10 fx","30 Gy/10 fx"),("40 Gy/15 fx","40 Gy/15 fx"),("50 Gy/25 fx","50 Gy/25 fx"),("60 Gy/30 fx","60 Gy/30 fx")],"B",
    "Perry NEJM 2017：40 Gy/15 fx + TMZ 對老年 GBM 非劣，副作用較輕。","Perry NEJM 2017: 40 Gy/15 fx + TMZ is non-inferior with better tolerability in elderly GBM."),
  ("single","下列哪一項是 IDH-mut, 1p/19q co-del 的典型腫瘤？","Which tumor is typically IDH-mut and 1p/19q co-del?",
    [("Glioblastoma","Glioblastoma"),("Oligodendroglioma","Oligodendroglioma"),("Ependymoma","Ependymoma"),("Meningioma","Meningioma")],"B",
    "1p/19q co-del + IDH-mut 是 oligodendroglioma 的分子定義。","IDH mutation + 1p/19q co-deletion defines oligodendroglioma."),
  ("single","EF-14 (TTFields, Optune) 加到 TMZ 對 GBM 的效果？","EF-14 (TTFields, Optune) added to TMZ in GBM:",
    [("OS 無差別","No OS difference"),("提升約 5 個月 OS","~5-month OS improvement"),("僅提升 PFS 沒有 OS","PFS only, no OS"),("增加毒性且無效","Toxic and ineffective")],"B",
    "EF-14：TTFields + TMZ 相對 TMZ alone 提升 OS ~4.9 個月。","EF-14: TTFields + TMZ improves OS by ~4.9 months vs TMZ alone."),
  ("single","meningioma Grade 1 gross total resection 後標準處置？","Standard management of Grade 1 meningioma after gross total resection?",
    [("54 Gy RT","54 Gy RT"),("60 Gy RT","60 Gy RT"),("觀察 (observation)","Observation"),("Chemo","Chemotherapy")],"C",
    "WHO Grade 1 GTR 後 5-yr LC > 90%，觀察即可；Grade 2 或 STR 才考慮 RT。","WHO Grade 1 with GTR has >90% 5-yr LC — observation is standard; RT for Grade 2 or STR."),
  ("single","GBM 諮商時<strong>不應</strong>執行下列哪一項？","Which is <strong>NOT</strong> appropriate during a GBM consult?",
    [("Discuss Stupp regimen","Discuss Stupp regimen"),("Discuss MGMT status","Discuss MGMT status"),("Recommend CSI","Recommend CSI"),("Discuss TTFields option","Discuss TTFields option")],"C",
    "GBM 通常不進行 CSI；CSI 用於髓母細胞瘤等易播散 CSF 的病灶。","CSI is not used for GBM — reserved for CSF-disseminating tumors like medulloblastoma."),
  ("tf","是非題：所有 anaplastic astrocytoma (IDH-mut, Grade 3) 現在均建議 concurrent TMZ + RT。","True/False: All anaplastic astrocytoma (IDH-mut, Grade 3) currently receive concurrent TMZ + RT.","","F",
    "CATNON trial：adjuvant TMZ 對 IDH-mut anaplastic astrocytoma 提升 OS；concurrent TMZ 尚無證據。","CATNON: adjuvant TMZ improves OS for IDH-mut anaplastic astrocytoma; concurrent TMZ benefit not established."),
]}

# ----------------------- BRAIN METS -----------------------
QBANK["BrainMets"] = {"section_zh":"腦轉移","section_en":"Brain Metastases","questions":[
  ("single","RTOG 90-05 中，≤ 2 cm 腦轉移 SRS 單次劑量？","RTOG 90-05 single-fraction SRS dose for ≤ 2 cm brain met?",
    [("15 Gy","15 Gy"),("18 Gy","18 Gy"),("20 Gy","20 Gy"),("24 Gy","24 Gy")],"D",
    "RTOG 90-05：≤ 2 cm → 24 Gy；2.1–3 cm → 18 Gy；3.1–4 cm → 15 Gy。","RTOG 90-05: ≤ 2 cm → 24 Gy; 2.1–3 cm → 18 Gy; 3.1–4 cm → 15 Gy."),
  ("single","N09C4/NCCTG N0574 顯示 SRS + WBRT 相對 SRS alone？","N09C4/NCCTG N0574 showed that SRS + WBRT vs SRS alone had?",
    [("提升 OS","Improved OS"),("降低顱內失敗但認知較差","Reduced intracranial failure with worse cognition"),("提升認知功能","Better cognition"),("兩者結果相同","No difference in any outcome")],"B",
    "WBRT 降低遠端腦內失敗，但認知功能明顯較差，OS 相同 → 支持 SRS alone。","WBRT reduces distant intracranial failure but worsens cognition with no OS difference — supports SRS alone."),
  ("single","NRG CC001 對於 WBRT 的建議是？","NRG CC001 recommendation for WBRT is?",
    [("避免 memantine","Avoid memantine"),("使用 hippocampal-avoidance WBRT + memantine","Use hippocampal-avoidance WBRT + memantine"),("使用 60 Gy WBRT","Use 60 Gy WBRT"),("避免 WBRT","Avoid WBRT")],"B",
    "CC001：HA-WBRT + memantine 相對標準 WBRT + memantine 認知下降降低。","CC001: HA-WBRT + memantine reduces cognitive decline vs standard WBRT + memantine."),
  ("single","QUARTZ trial 對 NSCLC 差 PS 病人的結論？","QUARTZ (poor-PS NSCLC brain mets) conclusion?",
    [("WBRT 大幅提升 OS","WBRT substantially improves OS"),("WBRT 無 OS/QoL 好處","No OS or QoL benefit from WBRT"),("SRS 應優先","SRS should be first"),("Chemo 提升 QoL","Chemo improves QoL")],"B",
    "QUARTZ：差 PS 且 NSCLC 病人 WBRT 相較支持性治療沒有好處。","QUARTZ: In poor-PS NSCLC patients, WBRT provided no OS or QoL benefit over supportive care."),
  ("single","N107C (postop cavity SRS vs WBRT) 顯示？","N107C (postop cavity SRS vs WBRT) showed?",
    [("SRS 認知較好，OS 相同","SRS better cognition, similar OS"),("WBRT 提升 OS","WBRT improved OS"),("兩者認知相同","Equivalent cognition"),("SRS 更差 LC","SRS had worse LC")],"A",
    "N107C：術腔 SRS 認知功能顯著較好，OS 相似 → 術後首選 SRS。","N107C: Cavity SRS provides significantly better cognition with similar OS — preferred postop."),
]}

# ----------------------- HEAD & NECK -----------------------
QBANK["HeadNeck"] = {"section_zh":"頭頸部","section_en":"Head & Neck","questions":[
  ("single","RTOG 91-11 對局部晚期喉癌顯示哪一組保留喉部率最高？","RTOG 91-11 (locally advanced larynx) — highest larynx-preservation arm?",
    [("Induction chemo → RT","Induction chemo → RT"),("Concurrent chemoRT","Concurrent chemoRT"),("RT alone","RT alone"),("Total laryngectomy","Total laryngectomy")],"B",
    "Concurrent chemoRT (cis) 保留喉部率最高，OS 三組相當。","Concurrent chemoRT (cis) had the highest larynx preservation; OS was similar across arms."),
  ("single","RTOG 1016 對 HPV+ 口咽癌顯示？","RTOG 1016 in HPV+ OPC showed?",
    [("Cetuximab 非劣於 cisplatin","Cetuximab non-inferior to cisplatin"),("Cetuximab 差於 cisplatin","Cetuximab inferior to cisplatin"),("Cetuximab 優於 cisplatin","Cetuximab superior to cisplatin"),("兩者毒性相同","Same toxicity")],"B",
    "RTOG 1016：cetuximab OS 較差，cisplatin 仍為標準；不建議 de-escalate。","RTOG 1016: cetuximab was inferior to cisplatin in HPV+ OPC — cisplatin remains standard."),
  ("single","口咽癌高劑量 RT 標準處方為？","Standard high-dose RT for oropharynx cancer?",
    [("60 Gy/30 fx","60 Gy/30 fx"),("66 Gy/33 fx","66 Gy/33 fx"),("70 Gy/33–35 fx","70 Gy/33–35 fx"),("74 Gy/37 fx","74 Gy/37 fx")],"C",
    "definitive H&N chemoRT 標準 70 Gy/33–35 fx；elective node 54–63 Gy。","Standard definitive H&N chemoRT is 70 Gy/33–35 fx; elective nodes 54–63 Gy."),
  ("single","下列哪一種 H&N 癌症與 EBV 相關性最高？","Which H&N cancer is most strongly associated with EBV?",
    [("Oral cavity","Oral cavity"),("Oropharynx","Oropharynx"),("Nasopharynx","Nasopharynx"),("Larynx","Larynx")],"C",
    "NPC 與 EBV 相關；亞洲高發，血漿 EBV DNA 為預後 marker。","NPC is EBV-associated; endemic in Asia; plasma EBV DNA is a prognostic marker."),
  ("single","下列何者是 HPV+ 口咽癌預後標記？","Which is a good-prognosis marker for oropharynx cancer?",
    [("p16 陰性","p16 negative"),("p16 陽性","p16 positive"),("EGFR 過表現","EGFR overexpression"),("HPV E6 陰性","HPV E6 negative")],"B",
    "p16+ 是 HPV+ OPC 的替代標記，5-yr OS ~ 80–90%。","p16+ is a surrogate for HPV+ OPC — 5-yr OS ~80–90%."),
  ("single","下列 Level 淋巴結命名中，Level II 位於？","Level II nodes are located at?",
    [("Submental","Submental"),("Upper internal jugular (jugulodigastric)","Upper internal jugular (jugulodigastric)"),("Posterior triangle","Posterior triangle"),("Central compartment","Central compartment")],"B",
    "Level II = 上頸內 (jugulodigastric)，是 H&N 最常受累區域之一。","Level II = upper internal jugular (jugulodigastric) — commonly involved in H&N."),
  ("single","下列哪個劑量限制對<strong>parotid</strong>最合適？","Which is the recommended <strong>parotid</strong> constraint?",
    [("Mean ≤ 20 Gy","Mean ≤ 20 Gy"),("Mean ≤ 26 Gy","Mean ≤ 26 Gy"),("Mean ≤ 40 Gy","Mean ≤ 40 Gy"),("Dmax ≤ 50 Gy","Dmax ≤ 50 Gy")],"B",
    "Parotid mean ≤ 26 Gy 有助長期唾液分泌保留 (QUANTEC)。","QUANTEC: parotid mean ≤ 26 Gy preserves long-term saliva."),
  ("multi","定義 T1 glottic laryngeal cancer 的特徵？(多選)","Features of T1 glottic larynx? (Multiple)",
    [("侷限於聲帶","Confined to vocal cords"),("聲帶活動正常","Normal cord mobility"),("已侵及甲狀軟骨","Thyroid cartilage invasion"),("N+","N+ disease")],["A","B"],
    "T1 = 侷限聲帶且活動正常；甲狀軟骨侵犯屬 T4；N+ 為分期升級。","T1 = confined to cords with normal mobility; cartilage invasion = T4; N+ upstages."),
  ("single","T1a glottic laryngeal cancer 常用 RT 處方？","Common RT dose for T1a glottic larynx?",
    [("50 Gy/25 fx","50 Gy/25 fx"),("63 Gy/28 fx","63 Gy/28 fx"),("70 Gy/33 fx","70 Gy/33 fx"),("30 Gy/10 fx","30 Gy/10 fx")],"B",
    "T1 glottic 常用 63 Gy/28 fx (2.25 Gy) 或 66 Gy/33 fx；5-yr LC > 90%。","T1 glottic: 63 Gy/28 fx (2.25 Gy) or 66 Gy/33 fx — 5-yr LC > 90%."),
]}

# ----------------------- LUNG -----------------------
QBANK["Lung"] = {"section_zh":"肺癌","section_en":"Lung Cancer","questions":[
  ("single","RTOG 0617 對 stage III NSCLC 的關鍵發現？","Key finding of RTOG 0617 in stage III NSCLC?",
    [("74 Gy 優於 60 Gy","74 Gy superior to 60 Gy"),("74 Gy 差於 60 Gy","74 Gy inferior to 60 Gy"),("兩者 OS 相當","Equivalent OS"),("cetuximab 提升 OS","Cetuximab improved OS")],"B",
    "RTOG 0617：74 Gy 提升 OS 無效反而較差，60 Gy 仍為 stage III 標準。","RTOG 0617: 74 Gy had worse OS than 60 Gy — 60 Gy remains standard for stage III."),
  ("single","PACIFIC trial 的關鍵發現？","Key finding of PACIFIC?",
    [("Osimertinib consolidation 提升 OS","Osimertinib consolidation improved OS"),("Durvalumab consolidation 提升 OS","Durvalumab consolidation improved OS"),("Cetuximab consolidation 提升 OS","Cetuximab consolidation improved OS"),("Pembrolizumab consolidation 差","Pembrolizumab worse")],"B",
    "PACIFIC：Stage III unresectable chemoRT 後 durvalumab consolidation 提升 5-yr OS (43% vs 33%)。","PACIFIC: Durvalumab after chemoRT in stage III unresectable improves 5-yr OS (43% vs 33%)."),
  ("single","早期 NSCLC 醫學上不適合手術者標準治療？","Standard treatment for medically inoperable early-stage NSCLC?",
    [("60 Gy conventional","60 Gy conventional"),("SBRT","SBRT"),("SRS","SRS"),("Palliative RT","Palliative RT")],"B",
    "Medically inoperable stage I NSCLC 標準為 SBRT；BED > 100 Gy。","Medically inoperable stage I NSCLC standard = SBRT with BED > 100 Gy."),
  ("single","下列 SBRT 劑量哪一個是<strong>週邊</strong>肺癌常用處方？","Which is a common SBRT dose for a <strong>peripheral</strong> lung tumor?",
    [("50 Gy/5 fx","50 Gy/5 fx"),("54 Gy/3 fx","54 Gy/3 fx"),("60 Gy/8 fx","60 Gy/8 fx"),("70 Gy/10 fx","70 Gy/10 fx")],"B",
    "週邊 54 Gy/3 fx (RTOG 0236)；中心型 50 Gy/5 fx；超中心 60 Gy/8 fx。","Peripheral 54 Gy/3 fx (RTOG 0236); central 50 Gy/5 fx; ultracentral 60 Gy/8 fx."),
  ("single","LS-SCLC 標準 chemoRT 劑量／時程 (Turrisi)？","Standard LS-SCLC chemoRT dose (Turrisi)?",
    [("45 Gy BID / 3 weeks","45 Gy BID / 3 weeks"),("60 Gy QD / 6 weeks","60 Gy QD / 6 weeks"),("50 Gy QD / 5 weeks","50 Gy QD / 5 weeks"),("70 Gy QD / 7 weeks","70 Gy QD / 7 weeks")],"A",
    "Turrisi：45 Gy BID/3wk + cis/etop 為 LS-SCLC 標準；CONVERT 顯示 66 Gy QD 非劣。","Turrisi: 45 Gy BID/3wk + cis/etop is standard for LS-SCLC; CONVERT — 66 Gy QD non-inferior."),
  ("single","CONVERT trial 對 LS-SCLC 的結論？","CONVERT trial conclusion for LS-SCLC?",
    [("66 Gy QD 差於 45 Gy BID","66 Gy QD inferior to 45 Gy BID"),("66 Gy QD 非劣於 45 Gy BID","66 Gy QD non-inferior to 45 Gy BID"),("兩者不能替代","Not interchangeable"),("BID 已淘汰","BID obsolete")],"B",
    "CONVERT：66 Gy QD 與 45 Gy BID OS 相當 → 兩者均可為 LS-SCLC 選擇。","CONVERT: 66 Gy QD equivalent OS to 45 Gy BID — both acceptable for LS-SCLC."),
  ("single","LS-SCLC 完全反應者建議 PCI 劑量？","Recommended PCI dose in LS-SCLC complete responders?",
    [("15 Gy/5 fx","15 Gy/5 fx"),("25 Gy/10 fx","25 Gy/10 fx"),("30 Gy/15 fx","30 Gy/15 fx"),("40 Gy/20 fx","40 Gy/20 fx")],"B",
    "LS-SCLC CR 給 PCI 25 Gy/10 fx；降低腦轉率並提升 OS。","LS-SCLC CR: PCI 25 Gy/10 fx reduces brain mets and improves OS."),
  ("single","IMpower133 顯示 ES-SCLC 加入哪一種藥物提升 OS？","IMpower133 in ES-SCLC: adding which agent improved OS?",
    [("Atezolizumab","Atezolizumab"),("Ipilimumab","Ipilimumab"),("Cetuximab","Cetuximab"),("Ramucirumab","Ramucirumab")],"A",
    "IMpower133：atezolizumab + platinum/etoposide 提升 ES-SCLC OS。","IMpower133: adding atezolizumab to platinum/etoposide improves ES-SCLC OS."),
  ("single","CREST trial 對 ES-SCLC 顯示？","CREST trial (ES-SCLC) showed?",
    [("Thoracic RT 無效","Thoracic RT ineffective"),("Consolidation thoracic RT 提升 2-yr OS","Consolidative thoracic RT improves 2-yr OS"),("SBRT 為標準","SBRT is standard"),("PCI 無效","PCI ineffective")],"B",
    "CREST：ES-SCLC 化療反應後 consolidation thoracic RT 30 Gy/10 fx 提升 2-yr OS。","CREST: Consolidative thoracic RT (30 Gy/10 fx) after chemo response improves 2-yr OS in ES-SCLC."),
  ("multi","下列哪些是 stage III NSCLC concurrent chemoRT 常用化療方案？(多選)","Common chemo regimens for stage III NSCLC concurrent chemoRT? (Multiple)",
    [("Weekly carboplatin + paclitaxel","Weekly carboplatin + paclitaxel"),("Cisplatin + etoposide","Cisplatin + etoposide"),("FOLFOX","FOLFOX"),("Gemcitabine + cisplatin","Gemcitabine + cisplatin")],["A","B"],
    "常用方案：weekly carbo/paclitaxel 或 cis/etop q4wk；FOLFOX 為大腸癌方案。","Standard regimens: weekly carbo/paclitaxel or cis/etop q4wk; FOLFOX is for colorectal cancer."),
]}

# ----------------------- BREAST -----------------------
QBANK["Breast"] = {"section_zh":"乳癌","section_en":"Breast Cancer","questions":[
  ("single","FAST-Forward trial 對早期乳癌顯示什麼？","FAST-Forward showed what for early breast cancer?",
    [("50 Gy/25 fx 為最佳","50 Gy/25 fx best"),("26 Gy/5 fx 非劣於 40 Gy/15 fx","26 Gy/5 fx non-inferior to 40 Gy/15 fx"),("40 Gy/15 fx 差於 50 Gy","40 Gy/15 fx worse than 50 Gy"),("Boost 無需","Boost not required")],"B",
    "FAST-Forward：一週療程 26 Gy/5 fx 5 年局部控制與美觀非劣於 40 Gy/15 fx。","FAST-Forward: 1-week 26 Gy/5 fx is non-inferior at 5 yr to 40 Gy/15 fx."),
  ("single","EORTC 22881 boost trial 對哪一族群 boost 最有效？","EORTC 22881 boost trial — greatest benefit in which subgroup?",
    [("年紀 ≥ 60","Age ≥ 60"),("年紀 < 40","Age < 40"),("HER2+","HER2+"),("Node+","Node+")],"B",
    "Boost 降低所有年齡層復發，但年輕族群 (< 40) 絕對獲益最大。","Boost reduces recurrence at all ages but absolute benefit is largest in patients < 40."),
  ("single","PRIME II trial 建議哪一族群可省略 RT？","PRIME II — RT can be omitted in which population?",
    [("年輕，triple negative","Young, triple negative"),("≥ 65 歲, T1N0, ER+, low grade","Age ≥ 65, T1N0, ER+, low grade"),("BRCA carriers","BRCA carriers"),("DCIS high grade","High-grade DCIS")],"B",
    "PRIME II：≥ 65 歲、T1N0、ER+、low grade — RT 可省，OS 相同，LR 4.1% vs 1.3%。","PRIME II: RT can be omitted in age ≥ 65, T1N0, ER+, low grade — same OS; LR 4.1% vs 1.3%."),
  ("single","下列何者為 PMRT 的<strong>強</strong>適應症？","Which is a <strong>strong</strong> indication for PMRT?",
    [("2 cm N0 tumor","2 cm N0 tumor"),("≥ 4 positive nodes","≥ 4 positive nodes"),("Grade 1 DCIS","Grade 1 DCIS"),("Micrometastasis","Micrometastasis")],"B",
    "≥ 4 陽性淋巴、T3-4、切緣陽性為 PMRT 強適應症；1-3 陽性淋巴目前也常規建議。","≥ 4 positive nodes, T3-4, or positive margins are strong PMRT indications; 1–3 positive nodes also commonly indicated."),
  ("single","MA.20 對 node+ 乳癌顯示？","MA.20 in node+ breast cancer showed?",
    [("加 regional nodal RT 沒效","Regional nodal RT ineffective"),("Regional nodal RT (含 supraclav/IMN) 改善 DFS","Regional nodal RT (incl. supraclav/IMN) improves DFS"),("提升 30% OS","30% OS improvement"),("Boost 無效","Boost ineffective")],"B",
    "MA.20：node+ 病人加 IMN/medial supraclav 顯著提升 DFS。","MA.20: Adding IMN / medial supraclavicular RT in node+ breast cancer improves DFS."),
  ("single","BIG 3-07/TROG 07.01 顯示 DCIS 治療的什麼？","BIG 3-07/TROG 07.01 for DCIS showed?",
    [("Hypofractionation 差於 conventional","Hypofractionation inferior to conventional"),("Hypofractionation 非劣於 conventional","Hypofractionation non-inferior to conventional"),("Boost 無效","Boost ineffective"),("Mastectomy 優於 BCS","Mastectomy superior")],"B",
    "BIG 3-07：40 Gy/15 fx 對 DCIS 非劣於 50 Gy/25 fx。","BIG 3-07: 40 Gy/15 fx is non-inferior to 50 Gy/25 fx for DCIS."),
  ("multi","下列哪些是左乳 RT 常用降低心臟劑量的技術？(多選)","Which are common techniques to reduce cardiac dose in left breast RT? (Multiple)",
    [("DIBH","DIBH (deep inspiration breath-hold)"),("Prone positioning","Prone positioning"),("Proton therapy","Proton therapy"),("VMAT with all-anterior arcs","VMAT with all-anterior arcs")],["A","B","C"],
    "DIBH、俯臥、質子皆有效；VMAT 全前弧會增加低劑量散佈，不是首選降心臟劑量方法。","DIBH, prone, and protons all reduce cardiac dose; VMAT anterior arcs increase low-dose bath, not preferred for cardiac sparing."),
  ("single","triple-negative breast cancer 標準系統治療加入哪種免疫療法 (KEYNOTE-522)？","In TNBC (KEYNOTE-522), which immunotherapy is added?",
    [("Ipilimumab","Ipilimumab"),("Pembrolizumab","Pembrolizumab"),("Atezolizumab","Atezolizumab"),("Durvalumab","Durvalumab")],"B",
    "KEYNOTE-522：pembrolizumab + neoadjuvant chemo → adjuvant pembrolizumab 提升 EFS。","KEYNOTE-522: pembrolizumab + neoadj chemo → adjuvant pembrolizumab improves EFS in TNBC."),
  ("single","下列何者<strong>不是</strong> APBI (accelerated partial breast) 的候選？","Which patient is <strong>NOT</strong> a good candidate for APBI?",
    [("≥ 50 y, T1N0, ER+","Age ≥ 50, T1N0, ER+"),("多灶或廣泛 DCIS","Multifocal or extensive DCIS"),("Margin negative","Negative margins"),("Unifocal","Unifocal")],"B",
    "多灶病灶為 APBI 禁忌；ASTRO/ESTRO 標準：年長、小、ER+、切緣陰性、單一。","Multifocal disease is a contraindication to APBI; ideal candidates are older, small, ER+, negative-margin, unifocal."),
]}

# ----------------------- GI -----------------------
QBANK["GI"] = {"section_zh":"消化道","section_en":"Gastrointestinal","questions":[
  ("single","CROSS trial 對可切除食道癌的關鍵發現？","CROSS trial (resectable esophageal) key finding?",
    [("Preop chemoRT 無效","Preop chemoRT ineffective"),("Preop 41.4 Gy chemoRT + surgery 提升 OS","Preop 41.4 Gy chemoRT + surgery improves OS"),("Postop chemoRT 為標準","Postop chemoRT is standard"),("Surgery alone 相當","Surgery alone equivalent")],"B",
    "CROSS：Preop 41.4 Gy chemoRT + surgery OS 49 vs 24 mo。","CROSS: Preop 41.4 Gy chemoRT + surgery improves median OS (49 vs 24 mo)."),
  ("single","INT 0123 對 definitive esophageal chemoRT 顯示？","INT 0123 in definitive esophageal chemoRT?",
    [("64.8 Gy 優於 50.4 Gy","64.8 Gy superior"),("64.8 Gy 不優於 50.4 Gy","64.8 Gy NOT superior to 50.4 Gy"),("60 Gy 為新標準","60 Gy is new standard"),("Cisplatin 無效","Cisplatin ineffective")],"B",
    "INT 0123：higher dose 沒有 OS 好處 → 50.4 Gy 仍為 definitive 標準。","INT 0123: Higher dose (64.8 Gy) not superior to 50.4 Gy — 50.4 Gy remains standard."),
  ("single","Short-course preop RT for rectal cancer 的標準劑量／時程？","Standard short-course preop RT for rectal cancer?",
    [("25 Gy/5 fx","25 Gy/5 fx"),("30 Gy/10 fx","30 Gy/10 fx"),("45 Gy/25 fx","45 Gy/25 fx"),("50 Gy/25 fx","50 Gy/25 fx")],"A",
    "Swedish / Dutch TME 使用 25 Gy/5 fx 短程 RT 隨即手術。","Swedish/Dutch TME used 25 Gy/5 fx short-course RT followed by immediate surgery."),
  ("single","RAPIDO trial 對 locally advanced rectal cancer 顯示？","RAPIDO (LARC) key finding?",
    [("SCRT + consolidation chemo 提升 DFS","SCRT + consolidation chemo improves DFS"),("Long-course chemoRT 優於 SCRT","Long-course chemoRT superior to SCRT"),("Surgery alone 相當","Surgery alone equivalent"),("Chemo 無效","Chemo ineffective")],"A",
    "RAPIDO：SCRT + consolidation chemo 提升 pCR 與 DrTF；DFS/PFS 改善。","RAPIDO: SCRT + consolidation chemo improves pCR and disease-related treatment failure."),
  ("single","Nigro regimen for anal cancer 標準化療組合？","Nigro regimen chemotherapy for anal cancer?",
    [("5-FU + cisplatin","5-FU + cisplatin"),("5-FU + mitomycin C","5-FU + mitomycin C"),("Gemcitabine + cisplatin","Gemcitabine + cisplatin"),("FOLFOX","FOLFOX")],"B",
    "Nigro：5-FU + mitomycin C + RT，仍為肛門癌黃金標準。","Nigro regimen: 5-FU + mitomycin C + RT — remains the anal cancer gold standard."),
  ("single","RTOG 98-11 對 anal cancer 顯示？","RTOG 98-11 in anal cancer:",
    [("Cisplatin 優於 mitomycin","Cisplatin superior to mitomycin"),("Mitomycin + 5-FU 優於 cisplatin + 5-FU","Mitomycin + 5-FU superior to cisplatin + 5-FU"),("Neoadjuvant 化療有效","Induction chemo effective"),("Chemo 沒有幫助","Chemo not helpful")],"B",
    "RTOG 98-11：mitomycin + 5-FU 相對 cisplatin + 5-FU DFS 較好、colostomy rate 較低。","RTOG 98-11: mitomycin + 5-FU had better DFS and lower colostomy rate than cis + 5-FU."),
  ("single","LAP07 對 locally advanced pancreatic cancer 顯示？","LAP07 for LAPC showed?",
    [("ChemoRT 提升 OS","ChemoRT improves OS"),("ChemoRT 未提升 OS 但改善 LC","ChemoRT no OS benefit but improves LC"),("Chemo alone 差於 chemoRT","Chemo alone inferior to chemoRT"),("SBRT 無效","SBRT ineffective")],"B",
    "LAP07：4 個月化療後 chemoRT 相對 chemo 續行 OS 無差別但 LC 較好。","LAP07: After 4 mo chemo, chemoRT vs continued chemo — no OS difference but better LC."),
  ("multi","下列何者屬於 rectal cancer TNT 常用方案？(多選)","Which are common TNT regimens for rectal cancer? (Multiple)",
    [("RAPIDO (SCRT + consolidation chemo)","RAPIDO (SCRT + consolidation chemo)"),("PRODIGE 23 (induction FOLFIRINOX + chemoRT)","PRODIGE 23 (induction FOLFIRINOX + chemoRT)"),("Short-course RT alone","Short-course RT alone"),("Chemo alone","Chemo alone")],["A","B"],
    "TNT 兩大方案：RAPIDO 與 PRODIGE 23；純 RT 或純化療不是 TNT 定義。","The two major TNT schemes are RAPIDO and PRODIGE 23; RT alone or chemo alone is not TNT."),
  ("single","gastric cancer INT-0116 對術後結果的貢獻？","INT-0116 (gastric): postop chemoRT contribution?",
    [("有害無效","Ineffective"),("Postop chemoRT (5-FU/leucovorin) 提升 OS","Postop chemoRT improves OS"),("Postop chemo alone 較好","Postop chemo alone better"),("Preop 為標準","Preop is standard")],"B",
    "INT-0116：R0 gastric resection 後 5-FU + 45 Gy chemoRT 提升 OS。","INT-0116: After R0 gastric resection, adjuvant 5-FU + 45 Gy chemoRT improves OS."),
]}

# ----------------------- PROSTATE -----------------------
QBANK["Prostate"] = {"section_zh":"攝護腺癌","section_en":"Prostate Cancer","questions":[
  ("single","攝護腺 α/β 值大約為？","Prostate α/β ratio is approximately?",
    [("1.5","1.5"),("5","5"),("10","10"),("15","15")],"A",
    "攝護腺 α/β ~ 1.5，比多數腫瘤低，因此大分次生物學上有利。","Prostate α/β ~ 1.5 (unusually low) — favors hypofractionation biologically."),
  ("single","CHHiP trial 對局限性攝護腺癌顯示？","CHHiP trial (localized prostate) showed?",
    [("60 Gy/20 fx 非劣於 74 Gy/37 fx","60 Gy/20 fx non-inferior to 74 Gy/37 fx"),("60 Gy 差於 74 Gy","60 Gy inferior"),("Equivalent OS with better toxicity in 60 Gy","Equivalent OS with better toxicity in 60 Gy"),("60 Gy 提升 OS","60 Gy improves OS")],"A",
    "CHHiP：60 Gy/20 fx moderate hypofx 非劣於 74 Gy/37 fx，毒性相當。","CHHiP: 60 Gy/20 fx moderate hypofractionation is non-inferior to 74 Gy/37 fx with similar toxicity."),
  ("single","HYPO-RT-PC trial 對高風險攝護腺癌顯示？","HYPO-RT-PC trial (intermediate–high risk):",
    [("42.7 Gy/7 fx SBRT 非劣於 78 Gy/39 fx","42.7 Gy/7 fx SBRT non-inferior to 78 Gy/39 fx"),("SBRT 劣於 conventional","SBRT inferior"),("兩者毒性相同","Same toxicity"),("SBRT 需 ADT","SBRT requires ADT")],"A",
    "HYPO-RT-PC：ultra-hypofractionation 42.7 Gy/7 fx 非劣於 conventional。","HYPO-RT-PC: ultra-hypofractionation (42.7 Gy/7 fx) non-inferior to conventional."),
  ("single","高風險攝護腺癌長程 ADT 建議時長？","Long-course ADT duration for high-risk prostate cancer?",
    [("4 個月","4 months"),("6 個月","6 months"),("18–36 個月","18–36 months"),("永久","Indefinite")],"C",
    "高風險攝護腺癌長程 ADT 18–36 個月 (EORTC 22961, DART01/05)。","High-risk prostate: long-course ADT 18–36 mo (EORTC 22961, DART01/05)."),
  ("single","RTOG 9601 對 salvage RT 顯示 bicalutamide 加什麼？","RTOG 9601: adding bicalutamide to salvage RT?",
    [("縮短 RT 時程","Shorter RT course"),("提升 OS","Improved OS"),("降低 PSA","Reduced PSA"),("增加毒性但無效","Toxic and ineffective")],"B",
    "RTOG 9601：Salvage RT + 2-yr bicalutamide 相對 RT alone 提升 OS，主要獲益 PSA > 0.7。","RTOG 9601: Salvage RT + 2-yr bicalutamide improves OS vs RT alone, mainly if PSA > 0.7."),
  ("single","RADICALS-RT trial 對 adjuvant vs early salvage RT 的結論？","RADICALS-RT (adjuvant vs early salvage):",
    [("Adjuvant 顯著優於 salvage","Adjuvant significantly better"),("Early salvage 與 adjuvant 相當且毒性較低","Early salvage equivalent with less toxicity"),("Both toxic","Both toxic"),("Salvage 差","Salvage inferior")],"B",
    "RADICALS-RT / GETUG-17 / RAVES：早期 salvage 與 adjuvant biochemical PFS 相當、副作用較少。","RADICALS-RT / GETUG-17 / RAVES: early salvage equivalent to adjuvant bPFS with less toxicity."),
  ("single","STAMPEDE 顯示 metastatic 攝護腺癌加入 RT 到<strong>低量</strong>轉移的結論？","STAMPEDE — prostate RT in low-metastatic-burden mHSPC:",
    [("無 OS 好處","No OS benefit"),("提升 OS","Improves OS"),("增加副作用而無效","Toxic and ineffective"),("僅 fPFS 提升","Only fPFS improved")],"B",
    "STAMPEDE arm H：Low-burden mets 患者加入 prostate RT 提升 OS。","STAMPEDE arm H: In low-burden metastatic disease, adding prostate RT improves OS."),
  ("single","EORTC 22961 對 locally advanced 攝護腺癌 ADT 時長顯示？","EORTC 22961 ADT duration in locally advanced prostate?",
    [("36 個月 ADT 優於 6 個月","36 months superior to 6 months"),("6 個月 ADT 為足夠","6 months sufficient"),("兩者相同","Same OS"),("永久 ADT","Indefinite ADT")],"A",
    "EORTC 22961：locally advanced 高風險 36 個月 ADT 相對 6 個月提升 OS。","EORTC 22961: In locally advanced high-risk prostate, 36 mo ADT superior to 6 mo."),
  ("single","PACE-B trial 對局部攝護腺癌 SBRT 顯示？","PACE-B (localized prostate SBRT):",
    [("SBRT 差於 conventional","SBRT inferior"),("36.25 Gy/5 fx SBRT 非劣於 conventional","36.25 Gy/5 fx SBRT non-inferior to conventional"),("SBRT 增加 GU 毒性","SBRT increases GU toxicity"),("SBRT 需 ADT","SBRT requires ADT")],"B",
    "PACE-B：SBRT 36.25 Gy/5 fx 非劣於 conventional 或 moderate hypofx。","PACE-B: SBRT 36.25 Gy/5 fx non-inferior to conventional or moderate hypofractionation."),
  ("multi","下列哪些為 NCCN 高風險攝護腺癌特徵？(多選)","Which are NCCN high-risk prostate features? (Multiple)",
    [("PSA > 20","PSA > 20"),("Gleason ≥ 8 (GG ≥ 4)","Gleason ≥ 8 (GG ≥ 4)"),("T3a+","T3a+"),("PSA density > 0.15","PSA density > 0.15")],["A","B","C"],
    "PSA > 20、GG ≥ 4、T3a+ 為高風險；PSA density 屬於次要指標。","PSA > 20, GG ≥ 4, T3a+ define high-risk; PSA density is secondary."),
]}

# ----------------------- GYN -----------------------
QBANK["Gyn"] = {"section_zh":"婦科腫瘤","section_en":"Gynecologic","questions":[
  ("single","局部晚期子宮頸癌標準治療組合？","Standard treatment for locally advanced cervical cancer?",
    [("Surgery alone","Surgery alone"),("Concurrent chemoRT + brachytherapy","Concurrent chemoRT + brachytherapy"),("Chemo alone","Chemo alone"),("RT alone","RT alone")],"B",
    "Locally advanced cervical cancer：concurrent chemoRT + brachytherapy 為標準；weekly cisplatin。","Locally advanced cervical cancer: concurrent chemoRT (weekly cisplatin) + brachytherapy is standard."),
  ("single","EMBRACE-I 顯示 image-guided brachytherapy 的效益？","EMBRACE-I: image-guided adaptive brachytherapy provides?",
    [("提升 LC，降低毒性","Better LC with less toxicity"),("僅提升 OS","OS only"),("Toxicity 更高","More toxicity"),("無差別","No difference")],"A",
    "EMBRACE-I：MRI-guided IGABT 提升 LC 與 pelvic control，毒性降低。","EMBRACE-I: MRI-guided IGABT improves LC and pelvic control with reduced toxicity."),
  ("single","PORTEC-1 對中風險 endometrioid endometrial 顯示？","PORTEC-1 (intermediate-risk endometrioid endometrial):",
    [("EBRT 降低局部復發但 OS 無差別","EBRT reduces LR without OS benefit"),("EBRT 提升 OS","EBRT improves OS"),("EBRT 增加毒性且無效","EBRT toxic and ineffective"),("Chemo 為標準","Chemo is standard")],"A",
    "PORTEC-1：中風險加 EBRT 降低 LR 但無 OS 好處。","PORTEC-1: EBRT reduces LR but no OS benefit in intermediate-risk."),
  ("single","PORTEC-2 顯示 vaginal brachytherapy vs EBRT？","PORTEC-2: vaginal brachytherapy vs EBRT:",
    [("VBT 差於 EBRT","VBT inferior"),("VBT 對 vaginal LR 相當於 EBRT 且毒性較低","VBT equivalent to EBRT for vaginal LR with less toxicity"),("EBRT 提升 OS","EBRT improves OS"),("兩者毒性相同","Same toxicity")],"B",
    "PORTEC-2：VBT 對 vaginal LR 非劣於 pelvic EBRT，毒性顯著較少。","PORTEC-2: VBT non-inferior to pelvic EBRT for vaginal LR with markedly less toxicity."),
  ("single","PORTEC-3 對高風險 endometrial 顯示？","PORTEC-3 (high-risk endometrial):",
    [("ChemoRT 差於 RT alone","ChemoRT inferior"),("ChemoRT 對 Stage III 提升 OS","ChemoRT improves OS in Stage III"),("Chemo alone 標準","Chemo alone standard"),("Both toxic","Both toxic")],"B",
    "PORTEC-3：Stage III / serous / clear cell — chemoRT 相對 RT alone 提升 OS。","PORTEC-3: ChemoRT improves OS in Stage III / serous / clear-cell endometrial."),
]}

# ----------------------- LYMPHOMA -----------------------
QBANK["Lymphoma"] = {"section_zh":"淋巴瘤","section_en":"Lymphoma","questions":[
  ("single","GHSG HD10 對 early stage favorable HL 建議劑量？","GHSG HD10 dose for early-stage favorable HL?",
    [("20 Gy","20 Gy"),("30 Gy","30 Gy"),("36 Gy","36 Gy"),("45 Gy","45 Gy")],"A",
    "HD10：ABVD × 2 + 20 Gy ISRT，5-yr FFTF ~ 90%。","HD10: ABVD × 2 + 20 Gy ISRT — 5-yr FFTF ~90%."),
  ("single","GHSG HD11 對 early stage unfavorable HL 建議劑量？","GHSG HD11 dose for early-stage unfavorable HL?",
    [("20 Gy","20 Gy"),("30 Gy","30 Gy"),("36 Gy","36 Gy"),("45 Gy","45 Gy")],"B",
    "HD11：ABVD × 4 + 30 Gy ISRT。","HD11: ABVD × 4 + 30 Gy ISRT."),
  ("single","下列何者是<strong>DLBCL R-CHOP × 6 後</strong>加 ISRT 的常用劑量？","Common ISRT dose after R-CHOP × 6 for DLBCL?",
    [("20 Gy","20 Gy"),("30 Gy","30 Gy"),("40 Gy","40 Gy"),("50 Gy","50 Gy")],"B",
    "DLBCL 加 ISRT 通常 30 Gy (bulky) 或 30–40 Gy (partial response)。","DLBCL: ISRT typically 30 Gy for bulky or 30–40 Gy for partial response."),
  ("single","FLYER trial 對 younger low-risk DLBCL 顯示？","FLYER (young low-risk DLBCL) showed?",
    [("R-CHOP × 4 非劣於 × 6","4 cycles R-CHOP non-inferior to 6"),("R-CHOP × 8 為標準","8 cycles standard"),("Radiotherapy 為必要","RT is required"),("Rituximab 無效","Rituximab ineffective")],"A",
    "FLYER：年輕、low-risk (aaIPI 0, non-bulky) DLBCL — 4 週期 R-CHOP + 2R 非劣於 6 週期。","FLYER: In young, low-risk DLBCL, 4 cycles R-CHOP + 2R non-inferior to 6."),
  ("single","Follicular lymphoma stage I/II 標準治療？","Standard treatment for stage I/II follicular lymphoma?",
    [("Chemo alone","Chemo alone"),("ISRT 24 Gy","ISRT 24 Gy"),("Watch and wait","Watch and wait"),("Rituximab alone","Rituximab alone")],"B",
    "Stage I/II FL 常以 ISRT 24 Gy 作為 curative-intent 治療。","Stage I/II FL — ISRT 24 Gy for curative intent."),
]}

# ----------------------- SARCOMA -----------------------
QBANK["Sarcoma"] = {"section_zh":"軟組織肉瘤","section_en":"Sarcoma","questions":[
  ("single","O'Sullivan Lancet 2002 比較 preop vs postop RT 對肢體 STS 的重要發現？","O'Sullivan Lancet 2002 (preop vs postop RT for extremity STS):",
    [("Preop 較高急性 wound complications","Preop had more acute wound complications"),("Postop 較高 wound","Postop had more wound complications"),("Both same complications","Same complications"),("Preop 提升 OS","Preop improved OS")],"A",
    "Preop 50 Gy 較多急性 wound (35% vs 17%)；Postop 60–66 Gy 較多長期 fibrosis/edema。","Preop 50 Gy — more acute wound complications; postop 60–66 Gy — more long-term fibrosis/edema."),
  ("single","VORTEX / NRG SARC (Wang) 對 STS 顯示 CTV margin 可縮短到？","VORTEX / NRG SARC (Wang) reduced STS CTV margin to?",
    [("3 cm","3 cm"),("5 cm","5 cm"),("8 cm","8 cm"),("10 cm","10 cm")],"A",
    "VORTEX / Wang trial：CTV 3 cm longitudinal 相當於歷史 5 cm。","VORTEX / Wang: CTV 3 cm longitudinal margin equivalent to historical 5 cm."),
  ("single","STRASS trial 對 retroperitoneal sarcoma preop RT 的結論？","STRASS trial (retroperitoneal sarcoma preop RT):",
    [("Preop RT 提升 OS","Preop RT improves OS"),("Preop RT 對 abdominal recurrence-free survival 沒有整體好處","No overall abdominal recurrence-free survival benefit"),("Preop RT 完全無效","Preop RT completely ineffective"),("Postop 較好","Postop better")],"B",
    "STRASS：Preop RT 對 abdominal RFS 沒有整體好處，但 liposarcoma 亞群可能有幫助。","STRASS: Preop RT — no overall abdominal RFS benefit; possible benefit in liposarcoma subgroup."),
]}

# ----------------------- SKIN -----------------------
QBANK["Skin"] = {"section_zh":"皮膚癌","section_en":"Skin Cancer","questions":[
  ("single","BCC / cSCC definitive RT 高劑量常用處方？","Common definitive RT dose for BCC / cSCC?",
    [("30 Gy/5 fx","30 Gy/5 fx"),("55 Gy/20 fx","55 Gy/20 fx"),("66 Gy/33 fx","66 Gy/33 fx"),("70 Gy/33 fx","70 Gy/33 fx")],"C",
    "常用 66 Gy/33 fx (2 Gy/fx)；elderly 常用 55 Gy/20 fx；palliative 30 Gy/5 fx。","Common: 66 Gy/33 fx; elderly 55 Gy/20 fx; palliative 30 Gy/5 fx."),
  ("single","下列哪一項為 cSCC 高風險，考慮輔助 RT？","Which is a high-risk cSCC feature warranting adjuvant RT?",
    [("Well-differentiated","Well-differentiated"),("Perineural invasion","Perineural invasion"),("< 2 cm","< 2 cm"),("No nodal disease","No nodal disease")],"B",
    "PNI、深度 > 6 mm、切緣陽性、bulky node 為高風險，考慮輔助 RT。","PNI, depth > 6 mm, positive margins, bulky nodes are high-risk features → adjuvant RT."),
  ("single","下列 melanoma trial 顯示術後 nodal RT？","ANZMTG 01.02/TROG 02.01 (nodal melanoma):",
    [("提升 OS","Improved OS"),("降低 LR 但無 OS 好處","Reduced LR without OS benefit"),("兩者無差別","No difference"),("增加毒性且無效","Ineffective and toxic")],"B",
    "ANZMTG 01.02：高風險節區術後 RT 降低 LR ~50%，OS 無差別，副作用明顯。","ANZMTG 01.02: Adjuvant nodal RT halves LR without OS benefit and meaningful toxicity."),
]}

# ----------------------- PEDS -----------------------
QBANK["Peds"] = {"section_zh":"兒童腫瘤","section_en":"Pediatric Oncology","questions":[
  ("single","Average-risk medulloblastoma CSI 劑量？","Average-risk medulloblastoma CSI dose?",
    [("18 Gy","18 Gy"),("23.4 Gy","23.4 Gy"),("36 Gy","36 Gy"),("54 Gy","54 Gy")],"B",
    "Average-risk: 23.4 Gy CSI + 後顱窩 boost 至 54 Gy + chemo (ACNS 0331)。","Average-risk: 23.4 Gy CSI + posterior fossa boost to 54 Gy + chemo (ACNS 0331)."),
  ("single","High-risk medulloblastoma CSI 劑量？","High-risk medulloblastoma CSI dose?",
    [("18 Gy","18 Gy"),("23.4 Gy","23.4 Gy"),("36 Gy","36 Gy"),("54 Gy","54 Gy")],"C",
    "High-risk: 36 Gy CSI + boost + chemo。","High-risk: 36 Gy CSI + boost + chemo."),
  ("single","ACNS 0331 對 average-risk medulloblastoma 顯示？","ACNS 0331 in average-risk medulloblastoma:",
    [("18 Gy CSI 非劣於 23.4 Gy","18 Gy CSI non-inferior to 23.4 Gy"),("減少 CSI 或後顱窩 boost 皆不安全","Reducing CSI or reducing PF boost was NOT safe"),("Proton 為標準","Proton is standard"),("Chemo 無效","Chemo ineffective")],"B",
    "ACNS 0331：不能將 CSI 降到 18 Gy，也不能只 boost tumor bed 而不涵蓋 posterior fossa。","ACNS 0331: Cannot reduce CSI to 18 Gy or limit boost to tumor bed only — full PF must be treated."),
  ("single","Ewing sarcoma definitive RT 劑量？","Ewing sarcoma definitive RT dose?",
    [("45 Gy","45 Gy"),("50.4 Gy","50.4 Gy"),("55.8 Gy","55.8 Gy"),("70 Gy","70 Gy")],"C",
    "Ewing definitive RT 55.8 Gy (COG AEWS1031)。","Ewing definitive RT 55.8 Gy (COG AEWS1031)."),
  ("single","Wilms tumor flank RT 劑量？","Wilms tumor flank RT dose?",
    [("10.8 Gy","10.8 Gy"),("21.6 Gy","21.6 Gy"),("30 Gy","30 Gy"),("50 Gy","50 Gy")],"A",
    "Wilms flank 10.8 Gy (Stage III/IV or unfavorable histology)；pulmonary mets whole-lung 12 Gy。","Wilms flank RT 10.8 Gy (Stage III/IV / unfavorable histology); whole-lung 12 Gy for lung mets."),
  ("single","Neuroblastoma 高風險 primary site RT 劑量？","High-risk neuroblastoma primary site RT dose?",
    [("14.4 Gy","14.4 Gy"),("21.6 Gy","21.6 Gy"),("36 Gy","36 Gy"),("54 Gy","54 Gy")],"B",
    "高風險 neuroblastoma：induction → surgery → 21.6 Gy → immunotherapy (dinutuximab)。","High-risk neuroblastoma: induction → surgery → 21.6 Gy → immunotherapy (dinutuximab)."),
  ("single","下列 rhabdomyosarcoma 哪個 Group 可省 RT？","Which rhabdomyosarcoma group can omit RT?",
    [("Group I embryonal (favorable)","Group I embryonal (favorable)"),("Group II","Group II"),("Group III","Group III"),("Group IV","Group IV")],"A",
    "IRSG：Group I embryonal (favorable) 可觀察；其他組別皆需 RT。","IRSG: Group I embryonal (favorable) can be observed; all others require RT."),
]}

# ----------------------- PALLIATIVE -----------------------
QBANK["Palliative"] = {"section_zh":"緩和放射治療","section_en":"Palliative Radiation","questions":[
  ("single","單次 8 Gy 相對 30 Gy/10 fx 對<strong>單純疼痛骨轉移</strong>顯示？","Single 8 Gy vs 30 Gy/10 fx for <strong>uncomplicated bone mets</strong>:",
    [("8 Gy 疼痛控制較差","8 Gy pain control inferior"),("Same pain response, higher retreatment with 8 Gy","Same pain response, higher retreatment with 8 Gy"),("30 Gy 增加毒性且無效","30 Gy toxic and ineffective"),("兩者相同 retreatment","Same retreatment rate")],"B",
    "Chow / RTOG 97-14：疼痛反應相當，但 8 Gy 再照率較高。","Chow / RTOG 97-14: Equivalent pain response; single 8 Gy has higher retreatment rate."),
  ("single","脊髓壓迫 Patchell 2005 trial 顯示手術 + RT vs RT alone？","Patchell (2005) cord compression — surgery + RT vs RT alone:",
    [("Surgery + RT 提升 ambulation 與 OS","Surgery + RT improves ambulation and OS"),("Surgery ineffective","Surgery ineffective"),("兩者相同","Same outcomes"),("RT alone 較好","RT alone better")],"A",
    "Patchell：Surgery + RT 相對 RT alone 顯著提升 ambulation 與存活。","Patchell: Surgery + RT significantly improves ambulation and survival vs RT alone."),
  ("single","SC.24 / CCTG 顯示 spine SBRT 24 Gy/2 fx 相對 20 Gy/5 fx？","SC.24: spine SBRT 24 Gy/2 fx vs 20 Gy/5 fx?",
    [("SBRT 完全疼痛反應率較高","SBRT gives higher complete pain response rate"),("Same pain response","Same pain response"),("SBRT 增加骨折而無效","SBRT causes fractures and is ineffective"),("Conventional 較好","Conventional better")],"A",
    "SC.24：Spine SBRT 24 Gy/2 fx 完全疼痛反應率顯著高於 20 Gy/5 fx。","SC.24: Spine SBRT 24 Gy/2 fx improves complete pain response vs 20 Gy/5 fx."),
  ("single","SVC 症候群<strong>最快</strong>緩解的處置為？","Which provides the <strong>fastest</strong> relief in SVC syndrome?",
    [("Chemotherapy","Chemotherapy"),("Endovascular stenting","Endovascular stenting"),("RT alone","RT alone"),("Steroids alone","Steroids alone")],"B",
    "Endovascular stenting 最快緩解；後續依原發癌決定 RT / chemo (SCLC → 化療優先)。","Endovascular stenting gives fastest relief; subsequent RT/chemo per primary (SCLC → chemo first)."),
]}

# ----------------------- GU -----------------------
QBANK["GU"] = {"section_zh":"泌尿生殖 (非攝護腺)","section_en":"GU (non-prostate)","questions":[
  ("single","Muscle-invasive bladder cancer (MIBC) 保留膀胱的<strong>三合一治療 (TMT)</strong> 組成？","Trimodality therapy (TMT) for MIBC includes?",
    [("TURBT + RT + chemo","TURBT + RT + chemo"),("Radical cystectomy + chemo","Radical cystectomy + chemo"),("RT + BCG","RT + BCG"),("Chemo + BCG","Chemo + BCG")],"A",
    "TMT = maximal TURBT + concurrent chemoRT，保留膀胱之選項。","TMT = maximal TURBT + concurrent chemoRT — bladder-preservation option."),
  ("single","BC2001 對膀胱 chemoRT 顯示？","BC2001 trial (bladder chemoRT):",
    [("RT + 5-FU/mitomycin 提升 locoregional DFS","RT + 5-FU/mitomycin improves locoregional DFS"),("Chemo 無效","Chemo ineffective"),("Both toxic","Both toxic"),("Cystectomy alone 較好","Cystectomy alone better")],"A",
    "BC2001：加入 5-FU + mitomycin 顯著提升 locoregional DFS。","BC2001: adding 5-FU + mitomycin significantly improves locoregional DFS."),
  ("single","Stage I testicular seminoma 常用<strong>單次</strong>系統性治療？","A common single-dose systemic option for stage I testicular seminoma is?",
    [("Cisplatin","Cisplatin"),("Carboplatin AUC 7 × 1","Carboplatin AUC 7 × 1"),("Doxorubicin","Doxorubicin"),("Etoposide × 3","Etoposide × 3")],"B",
    "Stage I seminoma：單次 carboplatin AUC 7 是 surveillance / RT 之外的選項。","Stage I seminoma: single-dose carboplatin AUC 7 is an option alongside surveillance / RT."),
  ("single","Stage IIA testicular seminoma dog-leg RT 常用劑量？","Stage IIA seminoma dog-leg RT dose?",
    [("20 Gy","20 Gy"),("30 Gy","30 Gy"),("36 Gy","36 Gy"),("45 Gy","45 Gy")],"B",
    "Stage IIA/B seminoma dog-leg 30 Gy；標準替代為 3-4 週期 BEP。","Stage IIA/B seminoma: dog-leg 30 Gy; alternative 3–4 cycles BEP."),
]}
