# -*- coding: utf-8 -*-
"""Radiation-oncology English→Chinese term substitution dictionary.
Applied greedy longest-first to produce readable ZH versions of trial data.
Not a full fluent translation — but preserves clinical meaning for reading.
"""
import re

# Ordered dictionary: longer phrases FIRST (matched greedily before shorter substrings).
# Keys are lowercase regex-compatible patterns; \b enforces word boundaries where possible.
PAIRS = [
    # ------------------ MULTI-WORD CLINICAL PHRASES ------------------
    (r"randomized controlled trial", "隨機對照試驗"),
    (r"randomised controlled trial", "隨機對照試驗"),
    (r"current standard of care", "目前標準治療"),
    (r"standard of care", "標準治療"),
    (r"overall there was no benefit", "整體而言無好處"),
    (r"continued to be administered", "仍應使用"),
    (r"longer-term follow-up is needed", "仍需更長期追蹤"),
    (r"longer term follow-up is needed", "仍需更長期追蹤"),
    (r"longer-term follow-up", "更長期追蹤"),
    (r"longer term follow-up", "更長期追蹤"),
    (r"longer follow-up", "更長期追蹤"),
    (r"additional endpoints", "其他終點"),
    (r"additional therapy", "其他治療"),
    (r"primary tumor", "原發腫瘤"),
    (r"local therapy", "局部治療"),
    (r"continues to rise", "持續上升"),
    (r"continue to rise", "持續上升"),
    (r"still poor", "仍不佳"),
    (r"notable adverse effects", "明顯不良反應"),
    (r"adverse effects", "不良反應"),
    (r"highest risk", "最高風險"),
    (r"up to", "最高可達"),
    (r"long-term follow-up", "長期追蹤"),
    (r"long term follow-up", "長期追蹤"),
    (r"short-term follow-up", "短期追蹤"),
    (r"short term follow-up", "短期追蹤"),
    (r"follow-up", "追蹤"),
    (r"follow up", "追蹤"),
    (r"closed early due to futility", "因無效趨勢而提前停止"),
    (r"closed early due to failures", "因失敗事件過多而提前停止"),
    (r"closed early", "提前停止"),
    (r"may be underpowered", "可能統計力不足"),
    (r"underpowered", "統計力不足"),
    (r"should be recommended", "建議使用"),
    (r"should be avoided", "應避免"),
    (r"addition of", "加入"),
    (r"added to", "加入"),
    (r"neoadjuvant chemotherapy", "術前化療"),
    (r"adjuvant chemotherapy", "輔助化療"),
    (r"neoadjuvant chemoradiation", "術前化學放射治療"),
    (r"neoadjuvant chemoradiotherapy", "術前化學放射治療"),
    (r"adjuvant chemoradiation", "輔助化學放射治療"),
    (r"adjuvant chemoradiotherapy", "輔助化學放射治療"),
    (r"concurrent chemoradiation", "同步化學放射治療"),
    (r"concurrent chemoradiotherapy", "同步化學放射治療"),
    (r"chemoradiation", "化學放射治療"),
    (r"chemoradiotherapy", "化學放射治療"),
    (r"chemoradiaton", "化學放射治療"),
    (r"radiation therapy", "放射治療"),
    (r"radiotherapy", "放射治療"),
    (r"radiation oncology", "放射腫瘤"),
    (r"whole brain radiotherapy", "全腦放射治療"),
    (r"whole breast radiotherapy", "全乳放射治療"),
    (r"whole breast irradiation", "全乳照射"),
    (r"partial breast irradiation", "部分乳房照射"),
    (r"whole pelvis radiotherapy", "全骨盆放射治療"),
    (r"pelvic radiotherapy", "骨盆放射治療"),
    (r"post-mastectomy radiotherapy", "乳房切除後放射治療"),
    (r"post-mastectomy radiation", "乳房切除後放射治療"),
    (r"breast conserving surgery", "保乳手術"),
    (r"breast-conserving surgery", "保乳手術"),
    (r"breast conservation", "保乳"),
    (r"radical mastectomy", "根治性乳房切除"),
    (r"radical prostatectomy", "根治性攝護腺切除"),
    (r"radical hysterectomy", "根治性子宮切除"),
    (r"radical nephrectomy", "根治性腎切除"),
    (r"radical cystectomy", "根治性膀胱切除"),
    (r"radical resection", "根治性切除"),
    (r"gross total resection", "完全切除"),
    (r"subtotal resection", "部分切除"),
    (r"maximal safe resection", "最大安全切除"),
    (r"complete response", "完全反應"),
    (r"partial response", "部分反應"),
    (r"stable disease", "疾病穩定"),
    (r"progressive disease", "疾病進展"),
    (r"disease-free survival", "無病存活期"),
    (r"disease free survival", "無病存活期"),
    (r"progression-free survival", "無疾病進展存活期"),
    (r"progression free survival", "無疾病進展存活期"),
    (r"overall survival", "整體存活期"),
    (r"cancer-specific survival", "癌症特異存活期"),
    (r"cancer specific survival", "癌症特異存活期"),
    (r"biochemical recurrence", "生化復發"),
    (r"biochemical failure", "生化失敗"),
    (r"biochemical progression-free survival", "生化無進展存活期"),
    (r"biochemical relapse", "生化復發"),
    (r"local recurrence", "局部復發"),
    (r"local control", "局部控制"),
    (r"local-regional control", "局部區域控制"),
    (r"loco-regional control", "局部區域控制"),
    (r"locoregional control", "局部區域控制"),
    (r"local failure", "局部失敗"),
    (r"regional failure", "區域失敗"),
    (r"distant metastasis", "遠端轉移"),
    (r"distant metastases", "遠端轉移"),
    (r"distant failure", "遠端失敗"),
    (r"in-field recurrence", "野內復發"),
    (r"out-of-field recurrence", "野外復發"),
    (r"ipsilateral breast recurrence", "同側乳房復發"),
    (r"in-breast recurrence", "同側乳房復發"),
    (r"nodal recurrence", "淋巴結復發"),
    (r"positive margin", "切緣陽性"),
    (r"negative margin", "切緣陰性"),
    (r"close margin", "切緣接近"),
    (r"positive margins", "切緣陽性"),
    (r"negative margins", "切緣陰性"),
    (r"perineural invasion", "神經周圍侵犯"),
    (r"lymphovascular invasion", "淋巴血管侵犯"),
    (r"extracapsular extension", "包膜外侵犯"),
    (r"extranodal extension", "淋巴結外侵犯"),
    (r"seminal vesicle invasion", "精囊侵犯"),
    (r"nodal involvement", "淋巴結侵犯"),
    (r"positive nodes", "陽性淋巴結"),
    (r"positive lymph nodes", "陽性淋巴結"),
    (r"positive lymph node", "陽性淋巴結"),
    (r"negative lymph nodes", "陰性淋巴結"),
    (r"lymph node dissection", "淋巴結清掃"),
    (r"axillary lymph node dissection", "腋下淋巴結清掃"),
    (r"sentinel lymph node biopsy", "前哨淋巴結切片"),
    (r"sentinel lymph node", "前哨淋巴結"),
    (r"lymph node", "淋巴結"),
    (r"lymph nodes", "淋巴結"),
    (r"lumpectomy", "腫瘤切除"),
    (r"quadrantectomy", "象限切除"),
    (r"tumor bed", "腫瘤床"),
    (r"tumor bed boost", "腫瘤床加強照射"),
    (r"boost dose", "加強劑量"),
    (r"cavity boost", "術腔加強照射"),
    (r"posterior fossa boost", "後顱窩加強照射"),
    (r"nodal boost", "淋巴結加強照射"),
    (r"integrated boost", "整合加強照射"),
    (r"simultaneous integrated boost", "同步整合加強照射"),
    (r"sequential boost", "序貫加強照射"),
    (r"boost", "加強照射"),
    (r"pathologic complete response", "病理完全反應"),
    (r"pathological complete response", "病理完全反應"),
    (r"pathologic CR", "病理完全反應"),
    (r"pathologic response", "病理反應"),
    (r"clinical complete response", "臨床完全反應"),
    (r"acute toxicity", "急性毒性"),
    (r"late toxicity", "晚期毒性"),
    (r"grade 3 toxicity", "3 級毒性"),
    (r"grade 4 toxicity", "4 級毒性"),
    (r"grade 5 toxicity", "5 級毒性"),
    (r"adverse event", "不良事件"),
    (r"adverse events", "不良事件"),
    (r"quality of life", "生活品質"),
    (r"performance status", "表現狀態"),
    (r"cognitive function", "認知功能"),
    (r"cognitive decline", "認知功能下降"),
    (r"cognitive impairment", "認知功能障礙"),
    (r"cardiac toxicity", "心臟毒性"),
    (r"pulmonary toxicity", "肺部毒性"),
    (r"pneumonitis", "放射性肺炎"),
    (r"esophagitis", "食道炎"),
    (r"mucositis", "黏膜炎"),
    (r"dysphagia", "吞嚥困難"),
    (r"xerostomia", "口乾"),
    (r"proctitis", "直腸炎"),
    (r"cystitis", "膀胱炎"),
    (r"lymphedema", "淋巴水腫"),
    (r"radiation dermatitis", "放射性皮膚炎"),
    (r"skin toxicity", "皮膚毒性"),
    (r"fibrosis", "纖維化"),
    (r"secondary malignancy", "次發性惡性腫瘤"),
    (r"secondary malignancies", "次發性惡性腫瘤"),
    (r"secondary cancer", "次發癌"),
    # ---- Modalities & techniques ----
    (r"hypofractionated radiotherapy", "大分次放射治療"),
    (r"hypofractionation", "大分次照射"),
    (r"conventional fractionation", "傳統分次"),
    (r"ultrahypofractionation", "超大分次"),
    (r"ultra-hypofractionation", "超大分次"),
    (r"moderate hypofractionation", "中度大分次"),
    (r"accelerated fractionation", "加速分次"),
    (r"stereotactic body radiotherapy", "體部立體定位放射治療"),
    (r"stereotactic body radiation therapy", "體部立體定位放射治療"),
    (r"stereotactic ablative radiotherapy", "立體定位消融放射治療"),
    (r"stereotactic radiosurgery", "立體定位放射手術"),
    (r"intensity modulated radiation therapy", "強度調控放射治療"),
    (r"intensity-modulated radiation therapy", "強度調控放射治療"),
    (r"image guided radiation therapy", "影像導引放射治療"),
    (r"image-guided radiation therapy", "影像導引放射治療"),
    (r"proton therapy", "質子治療"),
    (r"proton beam therapy", "質子束治療"),
    (r"carbon ion therapy", "碳離子治療"),
    (r"brachytherapy", "近接治療"),
    (r"external beam radiotherapy", "體外放射治療"),
    (r"external beam radiation", "體外放射治療"),
    (r"external-beam radiotherapy", "體外放射治療"),
    (r"total body irradiation", "全身照射"),
    (r"craniospinal irradiation", "顱脊照射"),
    (r"prophylactic cranial irradiation", "預防性顱部照射"),
    (r"deep inspiration breath hold", "深吸氣憋氣"),
    (r"cone beam CT", "錐狀束 CT"),
    (r"cone-beam CT", "錐狀束 CT"),
    # ---- Agents / systemic ----
    (r"androgen deprivation therapy", "雄性素剝奪治療"),
    (r"anti-androgen therapy", "抗雄性素治療"),
    (r"hormonal therapy", "內分泌治療"),
    (r"endocrine therapy", "內分泌治療"),
    (r"immunotherapy", "免疫治療"),
    (r"immune checkpoint inhibitor", "免疫檢查點抑制劑"),
    (r"checkpoint inhibitor", "檢查點抑制劑"),
    (r"chemotherapy", "化療"),
    (r"platinum-based chemotherapy", "鉑類化療"),
    (r"platinum based chemotherapy", "鉑類化療"),
    (r"targeted therapy", "標靶治療"),
    (r"tyrosine kinase inhibitor", "酪胺酸激酶抑制劑"),
    (r"maintenance therapy", "維持治療"),
    (r"induction chemotherapy", "誘導化療"),
    (r"induction therapy", "誘導治療"),
    (r"consolidation therapy", "鞏固治療"),
    (r"salvage therapy", "挽救治療"),
    (r"salvage RT", "挽救放射治療"),
    (r"salvage radiotherapy", "挽救放射治療"),
    # ---- Disease-site nouns ----
    (r"breast cancer", "乳癌"),
    (r"prostate cancer", "攝護腺癌"),
    (r"lung cancer", "肺癌"),
    (r"non-small cell lung cancer", "非小細胞肺癌"),
    (r"non small cell lung cancer", "非小細胞肺癌"),
    (r"small cell lung cancer", "小細胞肺癌"),
    (r"colorectal cancer", "大腸直腸癌"),
    (r"rectal cancer", "直腸癌"),
    (r"colon cancer", "大腸癌"),
    (r"esophageal cancer", "食道癌"),
    (r"oesophageal cancer", "食道癌"),
    (r"pancreatic cancer", "胰臟癌"),
    (r"gastric cancer", "胃癌"),
    (r"anal cancer", "肛門癌"),
    (r"hepatocellular carcinoma", "肝細胞癌"),
    (r"cholangiocarcinoma", "膽管癌"),
    (r"bladder cancer", "膀胱癌"),
    (r"kidney cancer", "腎癌"),
    (r"renal cell carcinoma", "腎細胞癌"),
    (r"testicular cancer", "睪丸癌"),
    (r"cervical cancer", "子宮頸癌"),
    (r"endometrial cancer", "子宮內膜癌"),
    (r"ovarian cancer", "卵巢癌"),
    (r"vulvar cancer", "外陰癌"),
    (r"vaginal cancer", "陰道癌"),
    (r"head and neck cancer", "頭頸癌"),
    (r"head & neck cancer", "頭頸癌"),
    (r"nasopharyngeal carcinoma", "鼻咽癌"),
    (r"nasopharyngeal cancer", "鼻咽癌"),
    (r"oropharyngeal cancer", "口咽癌"),
    (r"oral cavity cancer", "口腔癌"),
    (r"laryngeal cancer", "喉癌"),
    (r"hypopharyngeal cancer", "下咽癌"),
    (r"salivary gland cancer", "唾液腺癌"),
    (r"thyroid cancer", "甲狀腺癌"),
    (r"skin cancer", "皮膚癌"),
    (r"basal cell carcinoma", "基底細胞癌"),
    (r"squamous cell carcinoma", "鱗狀細胞癌"),
    (r"cutaneous squamous cell carcinoma", "皮膚鱗狀細胞癌"),
    (r"melanoma", "黑色素瘤"),
    (r"soft tissue sarcoma", "軟組織肉瘤"),
    (r"osteosarcoma", "骨肉瘤"),
    (r"Ewing sarcoma", "Ewing 肉瘤"),
    (r"rhabdomyosarcoma", "橫紋肌肉瘤"),
    (r"neuroblastoma", "神經母細胞瘤"),
    (r"Wilms tumor", "Wilms 腫瘤"),
    (r"medulloblastoma", "髓母細胞瘤"),
    (r"ependymoma", "室管膜瘤"),
    (r"craniopharyngioma", "顱咽管瘤"),
    (r"pituitary adenoma", "腦下垂體腺瘤"),
    (r"meningioma", "腦膜瘤"),
    (r"vestibular schwannoma", "前庭神經鞘瘤"),
    (r"acoustic neuroma", "聽神經瘤"),
    (r"glioblastoma", "膠質母細胞瘤"),
    (r"glioma", "膠質瘤"),
    (r"low-grade glioma", "低惡度膠質瘤"),
    (r"low grade glioma", "低惡度膠質瘤"),
    (r"high-grade glioma", "高惡度膠質瘤"),
    (r"anaplastic glioma", "退行性膠質瘤"),
    (r"anaplastic astrocytoma", "退行性星細胞瘤"),
    (r"oligodendroglioma", "寡樹突膠質細胞瘤"),
    (r"astrocytoma", "星細胞瘤"),
    (r"chordoma", "脊索瘤"),
    (r"lymphoma", "淋巴瘤"),
    (r"Hodgkin lymphoma", "霍奇金淋巴瘤"),
    (r"Hodgkin's lymphoma", "霍奇金淋巴瘤"),
    (r"non-Hodgkin lymphoma", "非霍奇金淋巴瘤"),
    (r"non-Hodgkin's lymphoma", "非霍奇金淋巴瘤"),
    (r"diffuse large B-cell lymphoma", "瀰漫性大 B 細胞淋巴瘤"),
    (r"follicular lymphoma", "濾泡性淋巴瘤"),
    (r"MALT lymphoma", "MALT 淋巴瘤"),
    (r"multiple myeloma", "多發性骨髓瘤"),
    (r"leukemia", "白血病"),
    (r"brain metastases", "腦轉移"),
    (r"brain metastasis", "腦轉移"),
    (r"bone metastases", "骨轉移"),
    (r"bone metastasis", "骨轉移"),
    (r"liver metastases", "肝轉移"),
    (r"lung metastases", "肺轉移"),
    (r"oligometastatic disease", "寡轉移"),
    (r"oligometastases", "寡轉移"),
    (r"oligometastasis", "寡轉移"),
    (r"metastatic disease", "轉移性疾病"),
    (r"locally advanced", "局部晚期"),
    (r"locoregionally advanced", "局部區域晚期"),
    (r"advanced disease", "晚期疾病"),
    (r"early-stage", "早期"),
    (r"early stage", "早期"),
    (r"stage I", "第 I 期"),
    (r"stage II", "第 II 期"),
    (r"stage III", "第 III 期"),
    (r"stage IV", "第 IV 期"),
    # ---- Verbs / outcomes ----
    (r"significantly improved", "顯著提升"),
    (r"significantly reduced", "顯著降低"),
    (r"significantly increased", "顯著增加"),
    (r"significantly decreased", "顯著降低"),
    (r"was superior to", "優於"),
    (r"was inferior to", "劣於"),
    (r"non-inferior to", "非劣於"),
    (r"noninferior to", "非劣於"),
    (r"equivalent to", "相當於"),
    (r"comparable to", "相當於"),
    (r"associated with", "與……相關"),
    (r"correlated with", "與……相關"),
    (r"resulted in", "帶來"),
    (r"results in", "帶來"),
    (r"led to", "帶來"),
    (r"leads to", "帶來"),
    (r"lead to", "帶來"),
    (r"findings suggest that", "結果顯示"),
    (r"findings suggest", "結果顯示"),
    (r"suggests that", "顯示"),
    (r"suggest that", "顯示"),
    (r"acceptable for some patients", "對部分病人可接受"),
    (r"acceptable for some", "對部分病人可接受"),
    (r"acceptable", "可接受"),
    (r"not required", "不需要"),
    (r"directed to", "針對"),
    (r"appeared to", "看來"),
    (r"seemed to", "似乎"),
    (r"seem to", "似乎"),
    (r"designed as", "設計為"),
    (r"improved outcomes", "改善預後"),
    (r"improved survival", "改善存活"),
    (r"improved OS", "改善整體存活"),
    (r"improved DFS", "改善無病存活"),
    (r"improved PFS", "改善無疾病進展存活"),
    (r"improved LC", "改善局部控制"),
    (r"improved local control", "改善局部控制"),
    (r"no OS benefit", "無整體存活好處"),
    (r"no survival benefit", "無存活好處"),
    (r"no benefit", "無好處"),
    (r"no difference", "無差別"),
    (r"no significant difference", "無顯著差異"),
    (r"did not improve", "未改善"),
    (r"failed to improve", "未能改善"),
    (r"reduced local recurrence", "降低局部復發"),
    (r"reduced recurrence", "降低復發"),
    (r"reduced mortality", "降低死亡率"),
    (r"reduced toxicity", "降低毒性"),
    (r"increased toxicity", "增加毒性"),
    (r"improved local control", "改善局部控制"),
    (r"however", "然而"),
    (r"there was no", "沒有"),
    (r"there were no", "沒有"),
    # ---- Trial-language shortcuts ----
    (r"primary endpoint", "主要試驗終點"),
    (r"secondary endpoint", "次要試驗終點"),
    (r"primary outcome", "主要結果指標"),
    (r"median follow-up", "中位追蹤"),
    (r"median follow up", "中位追蹤"),
    (r"follow-up", "追蹤"),
    (r"follow up", "追蹤"),
    (r"5-year", "5 年"),
    (r"10-year", "10 年"),
    (r"5 year", "5 年"),
    (r"10 year", "10 年"),
    (r"hazard ratio", "風險比"),
    (r"odds ratio", "勝算比"),
    (r"relative risk", "相對風險"),
    (r"confidence interval", "信賴區間"),
    (r"statistically significant", "統計上顯著"),
    (r"not statistically significant", "統計上不顯著"),
    # ---- Bases / single-word terms ----
    (r"patients", "病人"),
    (r"patient", "病人"),
    (r"treatment", "治療"),
    (r"surgery", "手術"),
    (r"resection", "切除"),
    (r"observation", "觀察"),
    (r"surveillance", "監測"),
    (r"recurrence", "復發"),
    (r"relapse", "復發"),
    (r"mortality", "死亡率"),
    (r"toxicity", "毒性"),
    (r"survival", "存活"),
    (r"tumor", "腫瘤"),
    (r"tumour", "腫瘤"),
    (r"malignancy", "惡性腫瘤"),
    (r"benign", "良性"),
    (r"malignant", "惡性"),
    (r"metastatic", "轉移性"),
    (r"metastases", "轉移"),
    (r"metastasis", "轉移"),
    (r"randomized", "隨機分配"),
    (r"randomised", "隨機分配"),
    (r"prospective", "前瞻性"),
    (r"retrospective", "回溯性"),
    (r"single-arm", "單臂"),
    (r"single arm", "單臂"),
    (r"phase I", "第一期"),
    (r"phase II", "第二期"),
    (r"phase III", "第三期"),
    (r"phase IV", "第四期"),
    (r"meta-analysis", "統合分析"),
    (r"systematic review", "系統性回顧"),
    (r"cohort", "世代"),
    (r"months", "個月"),
    (r"month", "個月"),
    (r"years", "年"),
    (r"weeks", "週"),
    (r"days", "天"),
    (r"benefit", "好處"),
    (r"risk", "風險"),
    (r"risks", "風險"),
    (r"harm", "傷害"),
    (r"effective", "有效"),
    (r"ineffective", "無效"),
    (r"safe", "安全"),
    (r"safety", "安全性"),
    (r"excellent", "極佳"),
    (r"favorable", "較佳"),
    (r"maintained", "維持"),
    (r"maintainted", "維持"),
    (r"warranted", "值得進一步研究"),
    (r"appears", "看來"),
    (r"appear", "看來"),
    (r"seems", "似乎"),
    (r"reasonable", "合理"),
    (r"recommended", "建議"),
    (r"individualized", "個別化"),
    (r"pending", "待公布"),
    (r"response", "反應"),
    (r"predictive", "預測性"),
    (r"predict", "預測"),
    (r"developed", "建立"),
    (r"validated", "驗證"),
    (r"reported", "報告"),
    (r"compare", "比較"),
    (r"overall", "整體"),
    (r"control", "控制"),
    (r"approach", "策略"),
    (r"investigation", "研究"),
    (r"additional", "額外"),
    (r"therapy", "治療"),
    (r"protocol", "方案"),
    (r"record", "記錄"),
    (r"designed", "設計"),
    (r"efficacy", "療效"),
    (r"outcome", "結果"),
    (r"outcomes", "結果"),
    (r"result", "結果"),
    (r"results", "結果"),
    (r"findings", "發現"),
    (r"finding", "發現"),
    (r"conclusion", "結論"),
    (r"conclusions", "結論"),
    (r"trial", "試驗"),
    (r"trials", "試驗"),
    (r"study", "研究"),
    (r"studies", "研究"),
    (r"arm", "組"),
    (r"arms", "組"),
    (r"group", "組"),
    (r"groups", "組"),
    (r"versus", "vs"),
    (r"induction", "誘導"),
    (r"consolidation", "鞏固"),
    (r"adjuvant", "輔助"),
    (r"neoadjuvant", "術前"),
    (r"concurrent", "同步"),
    (r"sequential", "序貫"),
    (r"and", "與"),
    # ---- Common connectives ----
    (r"compared with", "相較於"),
    (r"compared to", "相較於"),
    (r"as compared to", "相較於"),
    (r"as compared with", "相較於"),
    (r"in comparison with", "相較於"),
    (r"in comparison to", "相較於"),
    (r"was better than", "優於"),
    (r"was worse than", "劣於"),
    (r"was not different from", "與……無差異"),
    (r"did not differ from", "與……無差異"),
    (r"did not differ", "無差異"),
    (r"was not superior", "未優於"),
    (r"was not inferior", "非劣於"),
    (r"was not effective", "無效"),
    (r"was not associated with", "未與……相關"),
    (r"however", "然而"),
    (r"although", "雖然"),
    (r"despite", "儘管"),
    (r"nevertheless", "然而"),
    (r"whereas", "反之"),
    (r"could", "可"),
    (r"can", "可"),
    (r"would", "會"),
    (r"in patients with", "在……病人中"),
    (r"in patients", "在病人中"),
    (r"in the setting of", "在……情境下"),
    (r"following", "接續"),
    (r"prior to", "在……前"),
    (r"before", "在……前"),
    (r"after", "在……後"),
    (r"during", "在……期間"),
    (r"between", "……之間"),
    (r"at a median", "中位"),
    (r"at median", "中位"),
    (r"median", "中位"),
    (r"mean", "平均"),
    (r"were", "為"),
    (r"was", "為"),
    (r"is", "為"),
    (r"are", "為"),
    (r"has", "有"),
    (r"have", "有"),
    (r"had", "曾有"),
    (r"with", "合併"),
    (r"without", "不含"),
    (r"versus", "vs"),
    (r"or", "或"),
    (r"not", "並非"),
    (r"no", "無"),
    (r"more", "較多"),
    (r"less", "較少"),
    (r"greater", "較大"),
    (r"lower", "較低"),
    (r"higher", "較高"),
    (r"reduced", "降低"),
    (r"increased", "提升"),
    (r"decreased", "降低"),
    (r"improved", "改善"),
    (r"worsened", "惡化"),
    (r"showed", "顯示"),
    (r"demonstrated", "顯示"),
    (r"suggested", "顯示"),
    (r"found", "發現"),
    (r"concluded", "結論"),
    (r"received", "接受"),
    (r"underwent", "接受"),
    (r"treated", "治療"),
    (r"randomized to", "隨機分配至"),
    (r"assigned to", "分配至"),
    (r"included", "納入"),
    (r"enrolled", "納入"),
    (r"followed", "追蹤"),
    (r"observed", "觀察"),
    (r"reported", "報告"),
    (r"compared", "比較"),
    (r"significant", "顯著"),
    (r"significantly", "顯著地"),
    (r"insignificant", "不顯著"),
    (r"efficacy", "療效"),
    (r"toxicities", "毒性"),
    (r"complications", "併發症"),
    (r"complication", "併發症"),
    (r"morbidity", "併發症"),
    (r"but", "但"),
    (r"alone", "單獨"),
    (r"only", "僅"),
    (r"also", "也"),
    (r"as well", "也"),
    (r"as", "作為"),
    (r"such as", "例如"),
    (r"at", "於"),
    (r"of", "的"),
    (r"to", "至"),
    (r"the", ""),
    (r"a", ""),
    (r"an", ""),
    (r"this", "此"),
    (r"that", ""),
    (r"these", "這些"),
    (r"those", "那些"),
    (r"which", ""),
    (r"who", "何人"),
    (r"where", "何處"),
    (r"when", "當"),
    (r"why", "為何"),
    (r"how", "如何"),
    (r"benefited", "獲益"),
    (r"benefit from", "受益於"),
    (r"was similar", "相似"),
    (r"were similar", "相似"),
    (r"similar", "相似"),
    (r"different", "不同"),
    (r"differences", "差異"),
    (r"difference", "差異"),
    (r"equivalent", "相當"),
    (r"non-inferior", "非劣"),
    (r"superior", "優"),
    (r"inferior", "劣"),
    # Acronyms — keep English but ensure spacing OK
]

# Pre-compile regexes (word-boundary if pattern starts/ends with letters).
def compile_pair(pat, sub):
    # Always wrap with word boundaries when both ends are word-characters.
    starts_word = re.match(r'^\w', pat) is not None
    ends_word = re.search(r'\w$', pat) is not None
    esc = re.escape(pat)
    if starts_word and ends_word:
        return (re.compile(r'\b' + esc + r'\b', re.IGNORECASE), sub)
    return (re.compile(esc, re.IGNORECASE), sub)

# Sort by length descending so we substitute longest patterns first
PAIRS_SORTED = sorted(PAIRS, key=lambda x: -len(x[0]))
COMPILED = [compile_pair(p, s) for p, s in PAIRS_SORTED]

POST_REPLACEMENTS = [
    (re.compile(r"\bThere may be\b", re.IGNORECASE), "可能有"),
    (re.compile(r"\bthere may be\b", re.IGNORECASE), "可能有"),
    (re.compile(r"\bThere 為 無\b", re.IGNORECASE), "無"),
    (re.compile(r"\bthere 為 無\b", re.IGNORECASE), "無"),
    (re.compile(r"\bThere 為\b", re.IGNORECASE), "有"),
    (re.compile(r"\bthere 為\b", re.IGNORECASE), "有"),
    (re.compile(r"\bThere is no longer\b", re.IGNORECASE), "不再有"),
    (re.compile(r"\bthere is no longer\b", re.IGNORECASE), "不再有"),
    (re.compile(r"\bThere remains?\b", re.IGNORECASE), "仍"),
    (re.compile(r"\bthere remains?\b", re.IGNORECASE), "仍"),
    (re.compile(r"\bbenefits persist\b", re.IGNORECASE), "效益仍持續"),
    (re.compile(r"\bnot yet reported\b", re.IGNORECASE), "尚未報告"),
    (re.compile(r"\bworse than expected\b", re.IGNORECASE), "比預期差"),
    (re.compile(r"\bbetter than expected\b", re.IGNORECASE), "優於預期"),
    (re.compile(r"\bresults? in\b", re.IGNORECASE), "帶來"),
    (re.compile(r"\bresulted in\b", re.IGNORECASE), "帶來"),
    (re.compile(r"\bleads? 至\b", re.IGNORECASE), "帶來"),
    (re.compile(r"\bled 至\b", re.IGNORECASE), "帶來"),
    (re.compile(r"\bcorrelated 合併\b", re.IGNORECASE), "與"),
    (re.compile(r"\bcurrent standard 的 care\b", re.IGNORECASE), "目前標準治療"),
    (re.compile(r"\bstandard 的 care\b", re.IGNORECASE), "標準治療"),
    (re.compile(r"\bmay be\b", re.IGNORECASE), "可能"),
    (re.compile(r"\bshould be\b", re.IGNORECASE), "應"),
    (re.compile(r"\bf/u\b", re.IGNORECASE), "追蹤"),
    (re.compile(r"\blong[- ]term\b", re.IGNORECASE), "長期"),
    (re.compile(r"\bshort[- ]term\b", re.IGNORECASE), "短期"),
    (re.compile(r"\bimproves? rates? 的 ([^。；,.;:!?]+?)(?=(?:[。；,.;:!?]|$))", re.IGNORECASE), r"提高 \1 率"),
    (re.compile(r"\brates? 的 ([^。；,.;:!?]+?)(?=(?:[。；,.;:!?]|$))", re.IGNORECASE), r"\1 率"),
    (re.compile(r"\bAddition 的 ([^。；,.]+?) 至 ([^。；,.]+?) 改善", re.IGNORECASE), r"在 \2 中加入 \1 可改善"),
]


def polish_zh_output(text):
    s = text
    for rx, sub in POST_REPLACEMENTS:
        s = rx.sub(sub, s)
    s = re.sub(r"\s+([,.;:!?%])", r"\1", s)
    s = re.sub(r"([（(])\s+", r"\1", s)
    s = re.sub(r"\s+([）)])", r"\1", s)
    s = re.sub(r"\s{2,}", " ", s)
    return s.strip()

def translate_en_to_zh(text):
    """Apply term substitutions to render an English medical string in mixed ZH form."""
    if not text: return text
    s = text
    for rx, sub in COMPILED:
        s = rx.sub(sub, s)
    # Tidy spacing between CJK and Latin (basic pass)
    s = re.sub(r'([一-鿿])\s+([A-Za-z0-9])', r'\1 \2', s)
    s = re.sub(r'([A-Za-z0-9])\s+([一-鿿])', r'\1 \2', s)
    s = re.sub(r'\s{2,}', ' ', s)
    return polish_zh_output(s)

if __name__ == "__main__":
    tests = [
        "Concurrent chemoradiotherapy significantly improved overall survival compared with radiotherapy alone.",
        "Adjuvant chemotherapy reduced local recurrence but did not improve OS.",
        "Post-mastectomy radiotherapy in patients with 1-3 positive lymph nodes reduced mortality at 10 years.",
    ]
    for t in tests:
        print("EN:", t)
        print("ZH:", translate_en_to_zh(t))
        print()
